CONST = { "const" }
INT = { "int" }
VOID = { "void" }
IF = { "if" }
ELSE = { "else" }
WHILE = { "while" }
BREAK = { "break" }
CONTINUE = { "continue" }
RETURN = { "return" }
EQ = { "==" }
NEQ = { "!=" }
LT = { "<" }
GT = { ">" }
LE = { "<=" }
GE = { ">=" }

LINE_COMMENT = @{ "//" ~ (!NEWLINE ~ ANY)* ~ (NEWLINE | EOI) }

MULTILINE_COMMENT = @{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" }

COMMENT = _{ LINE_COMMENT | MULTILINE_COMMENT }

WHITESPACE = _{ (" " | "\t" | NEWLINE)+ }

PLUS = { "+" }
MINUS = { "-" }
MUL = { "*" }
DIV = { "/" }
MOD = { "%" }
ASSIGN = { "=" }
NOT = { "!" }
AND = { "&&" }
OR = { "||" }
L_PAREN = { "(" }
R_PAREN = { ")" }
L_BRACE = { "{" }
R_BRACE = { "}" }
L_BRACKT = { "[" }
R_BRACKT = { "]" }
COMMA = { "," }
SEMICOLON = { ";" }

IDENT = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

INTEGER_CONST = @{
    ("0x" | "0X") ~ ASCII_HEX_DIGIT+ |
    "0" ~ ASCII_OCT_DIGIT* |
    ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*
}

TOKEN = {
    LINE_COMMENT |
    MULTILINE_COMMENT |
    WHITESPACE |
    NEWLINE |
    CONST | INT | VOID | IF | ELSE | WHILE | BREAK | CONTINUE | RETURN |
    EQ | NEQ | LT | GT | LE | GE | PLUS | MINUS | MUL | DIV | MOD |
    ASSIGN | NOT | AND | OR | L_PAREN | R_PAREN | L_BRACE | R_BRACE |
    L_BRACKT | R_BRACKT | COMMA | SEMICOLON | IDENT | INTEGER_CONST
}

// 程序结构定义
program = { SOI ~ TOKEN* ~ EOI }
